### ISSUE TITLE
Grisu will be removed from base

### ISSUE THREAD

**Issue by isentropic** [JuliaGraphics/Showoff.jl#28]
https://github.com/JuliaLang/julia/blob/v1.6.0-beta1/NEWS.md#deprecated-or-removed

Grisu will be removed soon, I think this is a critical issue and needs to be addressed ASAP.

**Comment by timholy** [comment]
https://github.com/JuliaAttic/Grisu.jl

That said, there is a loss: there is considerably more latency when using the package than when it was in Base. That's because Base comes with a lot of methods precompiled all the way to native code. I have a branch that ports most of this to Ryu, but the "engineering" mode doesn't work. If you'd ~like~be willing to fix that, then we could remove the dependency on the Grisu package.

**Comment by isentropic** [comment]
@timholy Would you please give me some feedback on this PR then?
https://github.com/JuliaGraphics/Showoff.jl/pull/29

**Comment by timholy** [comment]
Closed by #35. Thanks for helping get this done!

**Comment by isentropic** [comment]
When should we expect a release for this?

**Comment by timholy** [comment]
How's yesterday, is that soon enough for you? https://github.com/JuliaRegistries/General/pull/31256

But TagBot here needs updating, as does CI.
