### ISSUE TITLE
showoff regression in Plots test examples

### ISSUE THREAD

**Issue by daschw** [JuliaGraphics/Showoff.jl#39]
With Showoff v0.3.1:
```julia
julia> showoff([0.0, 0.2, 0.4, 0.6000000000000001, 0.8])
5-element Array{String,1}:
 "0.0"
 "0.2"
 "0.4"
 "0.6"
 "0.8"
```
With Showoff v1.0.1:
```julia
julia> showoff([0.0, 0.2, 0.4, 0.6000000000000001, 0.8])
5-element Array{String,1}:
 "0.0000000000000000"
 "0.2000000000000000"
 "0.4000000000000000"
 "0.6000000000000001"
 "0.8000000000000000"
```

**Comment by isentropic** [comment]
Is this ryu or grisu?

**Comment by isentropic** [comment]
Adding one more zero 
```julia
julia> showoff([0.0, 0.2, 0.4, 0.60000000000000001, 0.8])
5-element Array{String,1}:
 "0.0"
 "0.2"
 "0.4"
 "0.6"
 "0.8"
```
Would this one digit inconsistency be a problem?

**Comment by isentropic** [comment]
we could reduce the precision threshold but is this really critical?

**Comment by daschw** [comment]
> Would this one digit inconsistency be a problem?

I think so, with Showoff v1.0.1 added to Plots, we get for example
```julia
using Plots
plot(rand(10))
```
![showoff](https://user-images.githubusercontent.com/16589944/111070699-20e86880-84d3-11eb-96ef-ec2d524eeef6.png)

**Comment by isentropic** [comment]
I think i got it fixed with https://github.com/JuliaGraphics/Showoff.jl/commit/aa0b23459ba3e228fa8db30f1b28b7ad1b8e12b9
Perhaps float32 conversion was not without a reason in [Grisu code](https://github.com/JuliaGraphics/Showoff.jl/blob/aa0b23459ba3e228fa8db30f1b28b7ad1b8e12b9/src/grisu.jl#L13)

According to my tests, now it works fine. Once you approve, we can release it I guess
